### PR TITLE
Revert "[vscoq1] bump vsce webpack webpack-cli"

### PR DESCRIPTION
**Pull request by Blaisorblade**
I haven't been able to investigate, but if I include this commit, I get `command 'extension.coq.interpretToPoint' not found` and the Extension Host log contains this:

```
2023-04-07 13:00:42.194 [error] Activating extension maximedenes.vscoq failed due to an error:
2023-04-07 13:00:42.194 [error] SyntaxError: Unexpected token ')'
	at n (/Users/pgiarrusso1/.vscode/extensions/maximedenes.vscoq-0.3.8/client/out/extension.js:14:142091)
	at 4192 (/Users/pgiarrusso1/.vscode/extensions/maximedenes.vscoq-0.3.8/client/out/extension.js:14:143197)
	at i (/Users/pgiarrusso1/.vscode/extensions/maximedenes.vscoq-0.3.8/client/out/extension.js:14:205906)
	at 5620 (/Users/pgiarrusso1/.vscode/extensions/maximedenes.vscoq-0.3.8/client/out/extension.js:14:40066)
	at i (/Users/pgiarrusso1/.vscode/extensions/maximedenes.vscoq-0.3.8/client/out/extension.js:14:205906)
	at 3056 (/Users/pgiarrusso1/.vscode/extensions/maximedenes.vscoq-0.3.8/client/out/extension.js:14:102114)
	at i (/Users/pgiarrusso1/.vscode/extensions/maximedenes.vscoq-0.3.8/client/out/extension.js:14:205906)
	at 9751 (/Users/pgiarrusso1/.vscode/extensions/maximedenes.vscoq-0.3.8/client/out/extension.js:2:24742)
	at i (/Users/pgiarrusso1/.vscode/extensions/maximedenes.vscoq-0.3.8/client/out/extension.js:14:205906)
	at 814 (/Users/pgiarrusso1/.vscode/extensions/maximedenes.vscoq-0.3.8/client/out/extension.js:2:10780)
	at i (/Users/pgiarrusso1/.vscode/extensions/maximedenes.vscoq-0.3.8/client/out/extension.js:14:205906)
	at 6275 (/Users/pgiarrusso1/.vscode/extensions/maximedenes.vscoq-0.3.8/client/out/extension.js:2:32308)
	at i (/Users/pgiarrusso1/.vscode/extensions/maximedenes.vscoq-0.3.8/client/out/extension.js:14:205906)
	at 6130 (/Users/pgiarrusso1/.vscode/extensions/maximedenes.vscoq-0.3.8/client/out/extension.js:2:67721)
	at i (/Users/pgiarrusso1/.vscode/extensions/maximedenes.vscoq-0.3.8/client/out/extension.js:14:205906)
	at /Users/pgiarrusso1/.vscode/extensions/maximedenes.vscoq-0.3.8/client/out/extension.js:14:206273
	at Object.<anonymous> (/Users/pgiarrusso1/.vscode/extensions/maximedenes.vscoq-0.3.8/client/out/extension.js:14:206380)
	at u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at c._load (node:electron/js2c/asar_bundle:5:13343)
	at m._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:124:14199)
	at h._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:11871)
	at I._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:11264)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.i [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:98)
	at E.rb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:13135)
	at async Promise.all (index 0)
```

### CODE REVIEW

**Comment by Blaisorblade** [comment]
cc @huynhtrankhanh @thery

**Comment by thery** [comment]
can you send `extension.js` so we can do a diff?

**Comment by Blaisorblade** [comment]
https://gist.github.com/Blaisorblade/481c81e451f31fe516eba85d6b0eabde should have the old and new version as the two revisions.

**Comment by Blaisorblade** [comment]
I updated from VSCode 1.77.1 to 1.77.2 and it seems fixed.

Some info below in case this reappears.

------

I agree `extension.js` itself seems syntactically fine, only a small portion changed. Past bugs like https://github.com/microsoft/vscode/issues/132777 and https://stackoverflow.com/a/75922127/53974 have similar symptoms and involve VSCode bugs — maybe the error is in the the syntax of _loaded_ code?

**Pull request closed without merging**
